### ISSUE TITLE
com.google.android.apps.docs.storage content provider is not supported

### ISSUE THREAD

**Issue by sebastian-philipp** [jenzz/ContentProviderHelper#3]
Hi,

I'm getting this exception when trying to open the `com.google.android.apps.docs.storage` content provider:

![screenshot_2015-05-15-15-00-26](https://cloud.githubusercontent.com/assets/2574405/7653098/91b5bd42-fb13-11e4-8c6a-290458f0cf47.png)

**Comment by k3b** [comment]
I added the missing permission in the https://github.com/k3b/ContentProviderHelper fork.
