### ISSUE TITLE
publish ContentProviderHelper in the android-opensource-appstore http://fdroid.org/ 

### ISSUE THREAD

**Issue by k3b** [jenzz/ContentProviderHelper#5]
Goal : publish ContentProviderHelper in the android-opensource-appstore http://fdroid.org/ 

ToDo:

* Create a branch "fdroid" 
* remove the "report-errors-and-send-them-home" (frdoid does not like this)
* remove permission internet (was needed only for error-reporting)
* 

I have already started this with https://github.com/k3b/ContentProviderHelper/tree/FDroid
but of course I will not publish it on fdroid if projectowner does not want it

**Comment by jenzz** [comment]
I have just added a [LICENSE](https://raw.githubusercontent.com/jenzz/ContentProviderHelper/master/LICENSE) to the project so feel free to publish your fork on F-Droid ✌️

**Comment by k3b** [comment]
ContentProviderHelper is now available in FDroid app store at https://f-droid.org/wiki/page/de.k3b.android.contentproviderhelper. The chages i made are licensed under gpl-v3+.

@jenzz : thankyou for releasing this valuable tool to the public domain.
