### ISSUE TITLE
A LICENSE file is missing

### ISSUE THREAD

**Issue by jorgecastillo** [jenzz/ContentProviderHelper#6]
Even if you choose to just let us see the code to review it or build our own app, without being able to distribute our modifications, a file making this clearer would be nice. Thanks for your time & have a nice day.

P.S. By the way your app is awesome.

**Comment by k3b** [comment]
I agree, it would be great to know what we are allowed to do with the code.

Would it be ok to continue to continue developing this code under gpl-v3 or Apache v2?

With #4 it should be possible to publish this app on fdroid.

As long as license is unclear i donot want to invest time to update the code ......

**Comment by jenzz** [comment]
Sorry guys. As you can see, I haven't touched this project for about 3 years now.

I will add a license soon so you can go wild. 😉

**Comment by k3b** [comment]
thanks a lot

**Comment by k3b** [comment]
Are there any new infos about the licence file?

**Comment by jenzz** [comment]
[LICENSE](https://raw.githubusercontent.com/jenzz/ContentProviderHelper/master/LICENSE) file added. Wollah!

**Comment by k3b** [comment]
perfect. thanks a lot

**Comment by ghost** [comment]
Thanks
